[master]
192.168.1.100 ansible_user=ubuntu

[workers]
192.168.1.101 ansible_user=ubuntu
192.168.1.102 ansible_user=ubuntu

[k8s:children]
master
workers

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/id_rsa
# Avoid SSH confirmation prompts in automation
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
